pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}
include ':app', ':termux-shared', ':terminal-emulator', ':terminal-view'
include ':packages:pkg1'
include ':packages:pkg2'
include ':packages:pkg3'
include ':packages:pkg4'
include ':packages:pkg5'
include ':packages:pkg6'
include ':packages:pkg7'
include ':packages:pkg8'
include ':packages:pkg9'
include ':packages:pkg10'
include ':packages:pkg11'
include ':packages:pkg12'
include ':packages:pkg13'
include ':packages:pkg14'
include ':packages:pkg15'
include ':packages:pkg16'
include ':packages:pkg17'
include ':packages:pkg18'
include ':packages:pkg19'
include ':packages:pkg20'
include ':packages:pkg21'
include ':packages:pkg22'
include ':packages:pkg23'
include ':packages:pkg24'
include ':packages:pkg25'
include ':packages:pkg26'
include ':packages:pkg27'
include ':packages:pkg28'
include ':packages:pkg29'
include ':packages:pkg30'
include ':packages:pkg31'
include ':packages:pkg32'
include ':packages:pkg33'
include ':packages:pkg34'
include ':packages:pkg35'
include ':packages:pkg36'
include ':packages:pkg37'
include ':packages:pkg38'
include ':packages:pkg39'
include ':packages:pkg40'
include ':packages:pkg41'
include ':packages:pkg42'
include ':packages:pkg43'
include ':packages:pkg44'
include ':packages:pkg45'
include ':packages:pkg46'
include ':packages:pkg47'
include ':packages:pkg48'
include ':packages:pkg49'
include ':packages:pkg50'
include ':packages:pkg51'
include ':packages:pkg52'
include ':packages:pkg53'
include ':packages:pkg54'
include ':packages:pkg55'
include ':packages:pkg56'
include ':packages:pkg57'
include ':packages:pkg58'
include ':packages:pkg59'
include ':packages:pkg60'
include ':packages:pkg61'
include ':packages:pkg62'
include ':packages:pkg63'
include ':packages:pkg64'
include ':packages:pkg65'
include ':packages:pkg66'
include ':packages:pkg67'
include ':packages:pkg68'
include ':packages:pkg69'
include ':packages:pkg70'
include ':packages:pkg71'
include ':packages:pkg72'
include ':packages:pkg73'
include ':packages:pkg74'
include ':packages:pkg75'
include ':packages:pkg76'
include ':packages:pkg77'
include ':packages:pkg78'
include ':packages:pkg79'
include ':packages:pkg80'
include ':packages:pkg81'
include ':packages:pkg82'
include ':packages:pkg83'
include ':packages:pkg84'
include ':packages:pkg85'
include ':packages:pkg86'
include ':packages:pkg87'
include ':packages:pkg88'
include ':packages:pkg89'
include ':packages:pkg90'
include ':packages:pkg91'
include ':packages:pkg92'
include ':packages:pkg93'
include ':packages:pkg94'
include ':packages:pkg95'
include ':packages:pkg96'
include ':packages:pkg97'
include ':packages:pkg98'
include ':packages:pkg99'
include ':packages:pkg100'
include ':packages:pkg101'
include ':packages:pkg102'
include ':packages:pkg103'
include ':packages:pkg104'
include ':packages:pkg105'
include ':packages:pkg106'
include ':packages:pkg107'
include ':packages:pkg108'
include ':packages:pkg109'
include ':packages:pkg110'
include ':packages:pkg111'
include ':packages:pkg112'
include ':packages:pkg113'
include ':packages:pkg114'
include ':packages:pkg115'
include ':packages:pkg116'
include ':packages:pkg117'
include ':packages:pkg118'
include ':packages:pkg119'
include ':packages:pkg120'
include ':packages:pkg121'
include ':packages:pkg122'
include ':packages:pkg123'
include ':packages:pkg124'
include ':packages:pkg125'
include ':packages:pkg126'
include ':packages:pkg127'
